# Generated by Django 5.0.4 on 2025-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('house', models.CharField(choices=[('Gryffindor', 'Gryffindor'), ('Hufflepuff', 'Hufflepuff'), ('Ravenclaw', 'Ravenclaw'), ('Slytherin', 'Slytherin'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Auror', 'Auror'), ('Death Eater', 'Death Eater'), ('Other', 'Other')], default='Other', max_length=20)),
                ('wand', models.CharField(blank=True, max_length=100, null=True)),
                ('patronus', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
