# Generated by Django 5.0.4 on 2025-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('types', models.ManyToManyField(related_name='pokemons', to='pokemon.type')),
            ],
        ),
    ]
